server:
  port: 9000
spring:
  application:
    name: authentication-service
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: mongo_db
      port: 27017
      #username: mavuzer
      #password: mongo
      database: test


custom:
  jwt:
    secret-key: mavuzerSecretKeyForJWTHS512SignatureAlgo
    expiration: 86400000
